[package]
name = "time-aware"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "livy-service"
path = "src/main.rs"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.0", features = ["derive"] } 